### PR TITLE
update dependencies

### LINKED ISSUE #418: update dependencies (breaking changes)
Looks like there are some big updates in dependencies from where this project currently sits, notably:

## Major version bumps

- sanic 20.x -> 21.x
- structlog 20.x -> 21.x
- ujson 2.x -> 4.x
- multidict 4.x -> 5.x
- chardet 3.x -> 4.x

## CVE patches

- pyyaml

## Other

- bunch of minor/patch releases
- sanic breaking out some of its built-in test modules into a separate library

---

so, the work to get all of this updated and validated is non-trivial. I started it mostly to get the CVE patch in, but because of how we are regenerating dependencies right now, its a "take all updates or leave it" type situation. Opening this issue to track the work for updating

### PR DESCRIPTION
**Pull request by edaniszewski**
This PR:
- Updates to the latest dependencies, pulling in a lot of updates with major version bumps and thus breaking changes
- Updates lots of things ranging from test expectations, app metadata layout, changed expectations about app global state, weird update to route referencing

I'm not overall pleased with the latest sanic updates because a lot has changed, and while the major version was bumped accordingly, some of these changes took a lot of effort to track down what was happening. while I'm sure there was good reason for the changes, they do step on how some of our tests were set up. I think longer term, its probably worth moving to fastapi, if only for the better openapi support, but thats neither here nor there.

The driver for this PR was to update pyyaml so we are using the version which fixes the CVE it has. 

A future PR will update how dependency management is done here so we can have more fine-grained control over updates.

fixes #418 

Note: I will **not** cut a new release of Synse Server after this because I still want to do some local testing to make sure nothing else is funky. Expect a new release for this in the coming weeks.

### CODE REVIEW

**Review by lazypower — APPROVED** [review]
I don't fully understand the updates in here. Looks like we added some error handling, refactored the middleware invocation, changed the app initializer  and added some tests. 

This LGTM but again i'm just understanding the vauge bits that have been updated and not the full scope of this upgrade.

**Comment by edaniszewski** [comment]
Yeah, so just to provide some context:

- the app initializing bits were updated so `app` is now global and not created by fn, as unit tests were bombing because they were being registered with the same name, and it looks like that now causes sanic errors
- the sanic test client is being removed from the main sanic code where it previously resided, and the client methods now return a request and response, hence the proliferation of `_, resp = ...` in test files
- sanic changes how data is stored internally so there are updates to how we get internal info for tests, such as registered routes
-  we can no longer call functions directly which are decorated by the `@route` decorator, as it now returns a tuple of metadata, so the `/devices/...` route had to be updated accordingly.
- structlog also changed some internals with how contextvars work, so tests had to be updated to reflect that

I think thats most of it. Probably some additional small things.

**Review by MatthewHink — APPROVED** [review]
LGTM
Sorry so late on this. The morning was an adventure.

**Comment by edaniszewski** [comment]
No worries., no big rush on getting this merged in anyway. Thanks for the reviews!

**Pull request merged**
